# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'round1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PIL import Image
from numpy import asarray
import cv2
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QRect(10, 30, 1920, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.Processing = QTabWidget(self.centralwidget)
        self.Processing.setGeometry(QRect(920, 260, 921, 251))
        self.Processing.setObjectName("Processing")
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QRect(0, 0, 901, 221))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(5)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setStyleStrategy(QFont.PreferAntialias)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QTableWidgetItem()
        item.setFlags(Qt.ItemIsSelectable|Qt.ItemIsEditable|Qt.ItemIsDragEnabled|Qt.ItemIsDropEnabled|Qt.ItemIsUserCheckable|Qt.ItemIsEnabled|Qt.ItemIsTristate)
        self.tableWidget_2.setItem(0, 1, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_2.setItem(4, 3, item)
        self.Processing.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_4 = QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QRect(0, 0, 911, 221))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(4)
        item = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        item.setBackground(QColor(255, 85, 127))
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QTableWidgetItem()
        brush = QBrush(QColor(255, 170, 0))
        brush.setStyle(Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget_4.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(295)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget_4.verticalHeader().setHighlightSections(True)
        self.Processing.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_3 = QTableWidget(self.tab_5)
        self.tableWidget_3.setGeometry(QRect(0, 0, 911, 221))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(5)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.tableWidget_3.setItem(4, 0, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(178)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(120)
        self.Processing.addTab(self.tab_5, "")

        ################ for video streaming ######################################

        self.frame = QLabel(self.centralwidget)
        self.frame.setGeometry(QRect(50, 180, 800, 600))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        
        ############################################################################
        
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(160, 817, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QRect(310, 820, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.Processing.setCurrentIndex(2)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#55aa00;\"> Flipkart Grid 3.0</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">The Eagle Eye</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\"> Central Monitoring System</span></p></body></html>"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Induct Station"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bot ID"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dispatch"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Shipment"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Location"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.Processing.setTabText(self.Processing.indexOf(self.tab), _translate("MainWindow", "Processing"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Induct Station"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "City"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.Processing.setTabText(self.Processing.indexOf(self.tab_2), _translate("MainWindow", "Yet to Dispatch"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Induct Station"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bot ID"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.Processing.setTabText(self.Processing.indexOf(self.tab_5), _translate("MainWindow", "Delivered"))
        self.Worker1 = Worker1()
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton.clicked.connect(self.StartFeed)
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.pushButton_2.clicked.connect(self.Worker1.stop)
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

        self.Worker1.ImageUpdate.connect(self.ImageUpdateSlot)

    def ImageUpdateSlot(self, Image1):
        self.frame.setPixmap(QPixmap.fromImage(Image1))

    def StartFeed(self):
        self.Worker1.start()

class Worker1(QThread):
    ImageUpdate = pyqtSignal(QImage)
    def run(self):
        self.ThreadActive = True
        Capture = cv2.VideoCapture(0)
        while self.ThreadActive:
            ret, frame = Capture.read()
            if ret:
                Image1 = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                FlippedImage = cv2.flip(Image1, 1)
                ConvertToQtFormat = QImage(FlippedImage.data, FlippedImage.shape[1], FlippedImage.shape[0], QImage.Format_RGB888)
                Pic = ConvertToQtFormat.scaled(800, 600, Qt.KeepAspectRatio)
                self.ImageUpdate.emit(Pic)

    def stop(self):
        self.ThreadActive = False
        Imagelogo = Image.open("apple.png")
        numpyarray = asarray(Imagelogo)
        Imagelogo = cv2.cvtColor(numpyarray, cv2.COLOR_BGR2RGB)
        #FlippedImage = cv2.flip(Imagelogo, 1)
        ConvertToQtFormat = QImage(Imagelogo.data, Imagelogo.shape[1], Imagelogo.shape[0], QImage.Format_RGB888)
        Pic = ConvertToQtFormat.scaled(800, 600, Qt.KeepAspectRatio)
        self.ImageUpdate.emit(Pic)
        self.quit()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
